//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareNinjas.TestOriented.Core {
    
    
    public partial class JavaMethod : Microsoft.VisualStudio.TextTemplating.TextTransformation {
        
        /// <summary>
        /// Initializes a new instance of the <see cref="JavaMethod"/> class.
        /// </summary>
        public JavaMethod() : 
                base() {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="JavaMethod"/> class
        /// using the specified <paramref name="formatProvider"/>
        /// </summary>
        public JavaMethod(System.IFormatProvider formatProvider) : 
                base(formatProvider) {
        }
        
        /// <summary>
        /// Generates the text output of the transformation.
        /// </summary>
        /// 
        /// <returns>
        /// A string representing the generated text output of the text template transformation process.
        /// </returns>
        /// 
        /// <remarks>
        /// The text template transformation process has two steps. In the first step, the text template transformation
        /// engine creates a class that is named the generated transformation class. In the second step, the engine
        /// compiles and executes the generated transformation class, to produce the generated text output. The engine
        /// calls <see cref="TransformText"/> on the compiled generated transformation class to execute the text
        /// template and generate the text output.
        /// </remarks>
        public override string TransformText() {
            
            #line 2 "JavaMethod.tt"
            this.Write("\r\n/**\r\n * Tests the <i>");
            
            #line default
            #line hidden
            
            #line 4 "JavaMethod.tt"
            this.Write( MethodName );
            
            #line default
            #line hidden
            
            #line 4 "JavaMethod.tt"
            this.Write("</i> method with\r\n * TODO: write about scenario\r\n */\r\n@Test public void ");
            
            #line default
            #line hidden
            
            #line 7 "JavaMethod.tt"
            this.Write( MethodName );
            
            #line default
            #line hidden
            
            #line 7 "JavaMethod.tt"
            this.Write("_TODO ( ) {\r\n");
            
            #line default
            #line hidden
            
            #line 8 "JavaMethod.tt"
            this.Write( Body );
            
            #line default
            #line hidden
            
            #line 8 "JavaMethod.tt"
            this.Write("\r\n}\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
}
