//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareNinjas.TestOriented.Core {
    
    
    public partial class TestMethod : Microsoft.VisualStudio.TextTemplating.TextTransformation {
        
        /// <summary>
        /// Initializes a new instance of the <see cref="TestMethod"/> class.
        /// </summary>
        public TestMethod() : 
                base() {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="TestMethod"/> class
        /// using the specified <paramref name="formatProvider"/>
        /// </summary>
        public TestMethod(System.IFormatProvider formatProvider) : 
                base(formatProvider) {
        }
        
        /// <summary>
        /// Generates the text output of the transformation.
        /// </summary>
        /// 
        /// <returns>
        /// A string representing the generated text output of the text template transformation process.
        /// </returns>
        /// 
        /// <remarks>
        /// The text template transformation process has two steps. In the first step, the text template transformation
        /// engine creates a class that is named the generated transformation class. In the second step, the engine
        /// compiles and executes the generated transformation class, to produce the generated text output. The engine
        /// calls <see cref="TransformText"/> on the compiled generated transformation class to execute the text
        /// template and generate the text output.
        /// </remarks>
        public override string TransformText() {
            
            #line 2 "TestMethod.tt"
            this.Write("\r\n/// <summary>\r\n/// Tests the <c>");
            
            #line default
            #line hidden
            
            #line 4 "TestMethod.tt"
            this.Write( Method.Name );
            
            #line default
            #line hidden
            
            #line 4 "TestMethod.tt"
            this.Write("</c> method with\r\n/// TODO: write about scenario\r\n/// </summary>\r\n[Test]\r\npublic " +
                    "void ");
            
            #line default
            #line hidden
            
            #line 8 "TestMethod.tt"
            this.Write( Method.Name );
            
            #line default
            #line hidden
            
            #line 8 "TestMethod.tt"
            this.Write("_TODO ( ) {\r\n\t// TODO: invoke ");
            
            #line default
            #line hidden
            
            #line 9 "TestMethod.tt"
            this.Write( Method.Name );
            
            #line default
            #line hidden
            
            #line 9 "TestMethod.tt"
            this.Write(" and assert properties of its effects/output\r\n\tAssert.Fail ( \"Test not yet writte" +
                    "n\" );\r\n}\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
}
